var	verses = ['Rejoice always, pray without ceasing, give thanks in all circumstances; for this is the will of God in Christ Jesus for you.', 'The Lord your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing.' , 'Rejoice in hope, be patient in tribulation, be constant in prayer.' , 'When the cares of my heart are many, your consolations cheer my soul.' , 'This is the day that the Lord has made; let us rejoice and be glad in it.' , 'Though the fig tree should not blossom, nor fruit be on the vines, the produce of the olive fail and the fields yield no food, the flock be cut off from the fold and there be no herd in the stalls, yet I will rejoice in the Lord; I will take joy in the God of my salvation.' , 'You make known to me the path of life; in your presence there is fullness of joy; at your right hand are pleasures forevermore.' , 'Though you have not seen him, you love him. Though you do not now see him, you believe in him and rejoice with joy that is inexpressible and filled with glory, obtaining the outcome of your faith, the salvation of your souls.' , 'I will greatly rejoice in the Lord; my soul shall exult in my God, for he has clothed me with the garments of salvation; he has covered me with the robe of righteousness, as a bridegroom decks himself like a priest with a beautiful headdress, and as a bride adorns herself with her jewels.' , 'Until now you have asked nothing in my name. Ask, and you will receive, that your joy may be full.' , 'Each one must give as he has decided in his heart, not reluctantly or under compulsion, for God loves a cheerful giver.' , 'To make an apt answer is a joy to a man, and a word in season, how good it is!' , 'Rejoice with those who rejoice, weep with those who weep.' , 'You are a hiding place for me; you preserve me from trouble; you surround me with shouts of deliverance. Selah' , 'For the sake of Christ, then, I am content with weaknesses, insults, hardships, persecutions, and calamities. For when I am weak, then I am strong.' , 'So that by Gods will I may come to you with joy and be refreshed in your company.' , 'Your testimonies are my heritage forever, for they are the joy of my heart.' , 'But godliness with contentment is great gain.' , 'And without faith it is impossible to please him, for whoever would draw near to God must believe that he exists and that he rewards those who seek him.' , 'For the Lord takes pleasure in his people; he adorns the humble with salvation.' , 'As for the rich in this present age, charge them not to be haughty, nor to set their hopes on the uncertainty of riches, but on God, who richly provides us with everything to enjoy.' , 'The father of the righteous will greatly rejoice; he who fathers a wise son will be glad in him.' 

]
 function newVerse() {
 	var	randomNumber = Math.floor(Math.random() * (verses.length));
 	document.getElementById('verseDisplay').innerHTML = verses[randomNumber]; 
 }

 var versesWorry = ['Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.', 'Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.', 'Casting all your anxieties on him, because he cares for you.' , 'Therefore I tell you, do not be anxious about your life, what you will eat or what you will drink, nor about your body, what you will put on. Is not life more than food, and the body more than clothing?' , 'Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble.' , 'When the cares of my heart are many, your consolations cheer my soul.' , 'Let not your hearts be troubled. Believe in God; believe also in me.' , 'Anxiety in a mans heart weighs him down, but a good word makes him glad.' , 'Peace I leave with you; my peace I give to you. Not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid.' , 'O Lord, all my longing is before you; my sighing is not hidden from you.' , 'And when they bring you to trial and deliver you over, do not be anxious beforehand what you are to say, but say whatever is given you in that hour, for it is not you who speak, but the Holy Spirit.' , 'Then Job arose and tore his robe and shaved his head and fell on the ground and worshiped. And he said Naked I came from my mothers womb, and naked shall I return. The Lord gave, and the Lord has taken away; blessed be the name of the Lord. ' , 'And God is able to make all grace abound to you, so that having all sufficiency in all things at all times, you may abound in every good work.' , 'And I heard a loud voice from the throne saying, Behold, the dwelling place of God is with man. He will dwell with them, and they will be his people, and God himself will be with them as their God. He will wipe away every tear from their eyes, and death shall be no more, neither shall there be mourning, nor crying, nor pain anymore, for the former things have passed away.']


 function newVerse2() {
 	var	randomNumber = Math.floor(Math.random() * (versesWorry.length));
 	document.getElementById('verseDisplay').innerHTML = versesWorry[randomNumber]; 
 }

var versesFear = ['Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.', 'When I am afraid, I put my trust in you.', 'Have I not commanded you? Be strong and courageous. Do not be frightened, and do not be dismayed, for the Lord your God is with you wherever you go.' , 'For I, the Lord your God, hold your right hand; it is I who say to you, Fear not, I am the one who helps you.' , 'And God is able to make all grace abound to you, so that having all sufficiency in all things at all times, you may abound in every good work.' , 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.' , 'Casting all your anxieties on him, because he cares for you.' , 'Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble.' , 'When the cares of my heart are many, your consolations cheer my soul.' , 'Let not your hearts be troubled. Believe in God; believe also in me.' , 'Anxiety in a mans heart weighs him down, but a good word makes him glad.' , 'Peace I leave with you; my peace I give to you. Not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid.' , 'O Lord, all my longing is before you; my sighing is not hidden from you.', 'And when they bring you to trial and deliver you over, do not be anxious beforehand what you are to say, but say whatever is given you in that hour, for it is not you who speak, but the Holy Spirit.' , 'Then Job arose and tore his robe and shaved his head and fell on the ground and worshiped. And he said  Naked I came from my mothers womb, and naked shall I return. The Lord gave, and the Lord has taken away; blessed be the name of the Lord.' , 'And God is able to make all grace abound to you, so that having all sufficiency in all things at all times, you may abound in every good work.' , 'And I heard a loud voice from the throne saying, Behold, the dwelling place of God is with man. He will dwell with them, and they will be his people, and God himself will be with them as their God. He will wipe away every tear from their eyes, and death shall be no more, neither shall there be mourning, nor crying, nor pain anymore, for the former things have passed away.']



 function newVerse3() {
 	var	randomNumber = Math.floor(Math.random() * (versesFear.length));
 	document.getElementById('verseDisplay').innerHTML = versesFear[randomNumber]; 
 }


 var versesSad = ['It is the Lord who goes before you. He will be with you; he will not leave you or forsake you. Do not fear or be dismayed.', 'For his anger is but for a moment, and his favor is for a lifetime. Weeping may tarry for the night, but joy comes with the morning.', 'Blessed are those who mourn, for they shall be comforted.' , 'When the righteous cry for help, the Lord hears and delivers them out of all their troubles. The Lord is near to the brokenhearted and saves the crushed in spirit.' , 'Casting all your anxieties on him, because he cares for you.' , 'O Lord, all my longing is before you; my sighing is not hidden from you.' , 'And I heard a loud voice from the throne saying, Behold, the dwelling place of God is with man. He will dwell with them, and they will be his people, and God himself will be with them as their God. He will wipe away every tear from their eyes, and death shall be no more, neither shall there be mourning, nor crying, nor pain anymore, for the former things have passed away.' , 'Rejoice with those who rejoice, weep with those who weep.' , 'Yet even now, declares the Lord, return to me with all your heart, with fasting, with weeping, and with mourning.' ,'Then Job arose and tore his robe and shaved his head and fell on the ground and worshiped. And he said, Naked I came from my mothers womb, and naked shall I return. The Lord gave, and the Lord has taken away; blessed be the name of the Lord.' , 'Turn back, and say to Hezekiah the leader of my people, Thus says the Lord, the God of David your father: I have heard your prayer; I have seen your tears. Behold, I will heal you. On the third day you shall go up to the house of the Lord.' , 'They shall hunger no more, neither thirst anymore; the sun shall not strike them, nor any scorching heat. For the Lamb in the midst of the throne will be their shepherd, and he will guide them to springs of living water, and God will wipe away every tear from their eyes.' , 'When I am afraid,I put my trust in you.' , 'Have I not commanded you? Be strong and courageous. Do not be frightened, and do not be dismayed, for the Lord your God is with you wherever you go.' , 'There is no fear in love, but perfect love casts out fear. For fear has to do with punishment, and whoever fears has not been perfected in love.']

 function newVerse4() {
 	var	randomNumber = Math.floor(Math.random() * (versesSad.length));
 	document.getElementById('verseDisplay').innerHTML = versesSad[randomNumber]; 
 }

var versesTempt = ['On reaching the place, he said to them, Pray that you will not fall into temptation. ' , 'And lead us not into temptation,but deliver us from the evil one.', 'No temptation has overtaken you that is not common to man. God is faithful, and he will not let you be tempted beyond your ability, but with the temptation he will also provide the way of escape, that you may be able to endure it.' , 'Blessed is the man who remains steadfast under trial, for when he has stood the test he will receive the crown of life, which God has promised to those who love him.' , 'Can one walk on hot coals and his feet not be scorched?' , 'And he said, “What comes out of a person is what defiles him. For from within, out of the heart of man, come evil thoughts, sexual immorality, theft, murder, adultery, coveting, wickedness, deceit, sensuality, envy, slander, pride, foolishness. All these evil things come from within, and they defile a person.”' , 'Let no one say when he is tempted, “I am being tempted by God,” for God cannot be tempted with evil, and he himself tempts no one.' , 'O Lord, all my longing is before you; my sighing is not hidden from you.' , 'Watch and pray that you may not enter into temptation. The spirit indeed is willing, but the flesh is weak.' , 'For you know that the testing of your faith produces steadfastness.' , 'Brothers, if anyone is caught in any transgression, you who are spiritual should restore him in a spirit of gentleness. Keep watch on yourself, lest you too be tempted.' , 'For forty days, being tempted by the devil. And Jesus ate nothing during those days. And when they were ended, he was hungry.' , 'For we do not have a high priest who is unable to sympathize with our weaknesses, but one who in every respect has been tempted as we are, yet without sin.']

 function newVerse5() {
 	var	randomNumber = Math.floor(Math.random() * (versesTempt.length));
 	document.getElementById('verseDisplay').innerHTML = versesTempt[randomNumber]; 
 }

var versesLove = ['Then he [Jesus] said to Thomas, Put your finger here; see my hands. Reach out your hand and put it into my side. Stop doubting and believe.', 'Jesus immediately reached out his hand and took hold of him, saying to him O you of little faith, why did you doubt? ', 'But let him ask in faith, with no doubting, for the one who doubts is like a wave of the sea that is driven and tossed by the wind.' , 'Truly, I say to you, whoever says to this mountain,  Be taken up and thrown into the sea,  and does not doubt in his heart, but believes that what he says will come to pass, it will be done for him.' , 'And Jesus answered them, Truly, I say to you, if you have faith and do not doubt, you will not only do what has been done to the fig tree, but even if you say to this mountain,  Be taken up and thrown into the sea,  it will happen.' , 'I will therefore that men pray every where, lifting up holy hands, without wrath and doubting.' , 'That according to the riches of his glory he may grant you to be strengthened with power through his Spirit in your inner being, so that Christ may dwell in your hearts through faith that you, being rooted and grounded in love.']

 function newVerse6() {
 	var	randomNumber = Math.floor(Math.random() * (versesLove.length));
 	document.getElementById('verseDisplay').innerHTML = versesLove[randomNumber]; 
 }

 